version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redisService
    ports:
      - "6379:6379"

  restapp:
    image: lucasmezza/restapp:$IMAGE_TAG
    container_name: restapp
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
