name: CI

on:
  push:
    branches: ["lucasMezza_p2_dev","lucasMezza_p2_base"]

  workflow_dispatch:

env: 
  SEM_VERSION:
  IMAGE_NAME:  restapp
  GITHUB_REF_NAME: ${{ github.ref_name }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  ## 🔧 1. 
  Static-codecheck:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install required python libraries
        run: | 
            pip install -r requirements.txt
            pip install flake8

      - name: Run Unit Tests
        run: python -m pytest test/unit -v

      - name: Code inspection (flake8)
        run: flake8 restapp

  ## 🔧 2. 
  Build:
    runs-on: self-hosted
    needs: Static-codecheck
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub 
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set env variables
        run: |
          $branchName = "${env:GITHUB_REF_NAME}" -replace '/', '-'
          $branchName = $branchName.ToLower()
          echo "BRANCH_NAME=$branchName" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "SEM_VERSION=${env:GITHUB_RUN_NUMBER}" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "IMAGE_TAG=$branchName-1.0.${env:GITHUB_RUN_NUMBER}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: build docker image
        run: docker build -t "restapp:$env:IMAGE_TAG" .

      - name: tag docker image
        run: docker tag "restapp:$env:IMAGE_TAG" "$env:DOCKER_USERNAME/restapp:$env:IMAGE_TAG"

      - name: push docker image
        run: docker push "$env:DOCKER_USERNAME/restapp:$env:IMAGE_TAG"

  ## 🚀 3. 
  deploy-dev:
    runs-on: self-hosted
    needs: Build
    environment:
      name: Develop
      url: http://localhost:5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set env variables
        run: | 
          $branchName = "${env:GITHUB_REF_NAME}" -replace '/', '-' 
          $branchName = $branchName.ToLower()
          echo "BRANCH_NAME=$branchName" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "SEM_VERSION=${env:GITHUB_RUN_NUMBER}" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "IMAGE_TAG=$branchName-1.0.${env:GITHUB_RUN_NUMBER}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Pull Redis image
        run: docker pull redis:alpine
 
      - name: Pull docker image  
        run:  docker pull "$env:DOCKER_USERNAME/restapp:$env:IMAGE_TAG"
 
      # - name: Stop and remove existing redisService container  
      #   run: |
      #     docker stop redisService 
      #     docker rm redisService

      # - name: Stop and remove existing docker container
      #   run: |
      #     docker stop restapp 
      #     docker rm  restapp

      - name: Generate .env file for docker-compose
        run: Set-Content -Path .env -Value "IMAGE_TAG=$env:IMAGE_TAG" -Encoding UTF8

      - name: Stop any existing containers  
        run: docker-compose down

      - name: Run with docker-compose 
        run: docker-compose up -d 

      - name: Run Integration Tests
        run: | 
          pip install -r requirements.txt
          python -m pytest test/integration -v

  ## 🚀 4. 
  deploy-prod:
    runs-on: self-hosted
    needs: deploy-dev
    if: github.ref == 'refs/heads/lucasMezza_p2_base'
    environment:
      name: Production
      url: http://localhost:5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set env variables  
        run: |
          $branchName = "${env:GITHUB_REF_NAME}" -replace '/', '-'
          $branchName = $branchName.ToLower()
          echo "BRANCH_NAME=$branchName" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "SEM_VERSION=${env:GITHUB_RUN_NUMBER}" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "IMAGE_TAG=$branchName-1.0.${env:GITHUB_RUN_NUMBER}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Pull Redis image
        run: docker pull redis:alpine
       
      - name: Pull docker image  
        run:  docker pull "$env:DOCKER_USERNAME/restapp:$env:IMAGE_TAG"

      - name: Stop and remove existing redisService container
        run: |
          docker stop redisService
          docker rm redisService

      - name: Stop and remove existing docker container
        run: |
          docker stop restapp
          docker rm  restapp

      - name: Generate .env file for docker-compose
        run: Set-Content -Path .env -Value "IMAGE_TAG=$env:IMAGE_TAG" -Encoding UTF8

      - name: Stop any existing containers  
        run: docker-compose down

      - name: Run with docker-compose 
        run: docker-compose up -d 
        
      - name: Run Integration Tests
        run: |
          pip install -r requirements.txt
          python -m pytest test/integration -v